platform :ios,'10.0'
target 'Smile' do
pod 'Moya', '~> 12.0'
pod 'RealmSwift'
pod "Texture"
pod "SnapKit"
pod 'NVActivityIndicatorView'
pod 'YPImagePicker',:git=>'https://github.com/JinchengKim/YPImagePicker'
pod 'CropViewController'
pod "Popover"
pod 'SnapSDK'
use_frameworks!
end
